// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using aspnetserver.Data;

#nullable disable

namespace aspnetserver.Data.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("aspnetserver.Data.Post", b =>
                {
                    b.Property<Guid>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PostId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostId = new Guid("cddd0057-ad45-458f-80d8-a6e1c9ff79e4"),
                            Content = "This is post 1 and it has some very interesting content. I have also liked to the video and subscribed",
                            Title = "Post 1"
                        },
                        new
                        {
                            PostId = new Guid("003cfcd1-aa14-4c11-bd0d-fcc7a90b29c3"),
                            Content = "This is post 2 and it has some very interesting content. I have also liked to the video and subscribed",
                            Title = "Post 2"
                        },
                        new
                        {
                            PostId = new Guid("4bb509be-6fdf-42ed-8297-2848dfd7c1ee"),
                            Content = "This is post 3 and it has some very interesting content. I have also liked to the video and subscribed",
                            Title = "Post 3"
                        },
                        new
                        {
                            PostId = new Guid("a4e9b455-36e1-4e2a-b40a-b165fd899227"),
                            Content = "This is post 4 and it has some very interesting content. I have also liked to the video and subscribed",
                            Title = "Post 4"
                        },
                        new
                        {
                            PostId = new Guid("9155b358-a674-4233-9b55-4b6786ca499c"),
                            Content = "This is post 5 and it has some very interesting content. I have also liked to the video and subscribed",
                            Title = "Post 5"
                        },
                        new
                        {
                            PostId = new Guid("7355c658-fe59-4f9c-a55b-edf54c4c8548"),
                            Content = "This is post 6 and it has some very interesting content. I have also liked to the video and subscribed",
                            Title = "Post 6"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
